### ISSUE TITLE
Suggestion: Consider using a map instead of a vector for `messages`

### ISSUE THREAD

**Issue by AbhinavOmprakash** [askonomm/shh#3]
Just a suggestion. 
Using a map for messages would enhance readability, especially when accessing elements, and would prevent code from breaking when you add elements to `messages`.

Here's an example
```clojure
(defn- delete!
  "Deletes an item from the database by a given `name`."
  [name]
  (init-db)
  ;; with keyword
  (println (:update messages ) name "...")
  (reset! db* (->> @db*
                   (filterv #(not (= (:name %) name)))))
  ;; with keyword
  (println (:delete messages))
  (System/exit 0))
```

If you'd like to proceed with this I wouldn't mind working on the PR

**Comment by askonomm** [comment]
Yeah the vector was a bit of a bad decision on my part for sure. Feel free to make a PR!

**Comment by askonomm** [comment]
Thought: what do you think of extracting the printing to a separate function, perhaps something called `say!` to which you have to pass the key only, and it would figure out what to display?

**Comment by AbhinavOmprakash** [comment]
These are the names of the keys I thought of, any changes to be made?

```clojure
(def messages
  { :name-of-pass     "Shh! What is the name of the password you are looking for?"
    :pass-not-found     "No such password found. Would you like to create one? (yes/no)"
    :create     "Creating a password called:"
    :desired-length     "What is the desired password length?"
    :copy     "Password copied!"
    :change     "Changing the password for:"
    :update     "Password updated."
    :delete      "Password deleted."})
```

**Comment by askonomm** [comment]
Looks good to me!

**Comment by askonomm** [comment]
My only thought was that since there are many prints, it is kind-of redundant to constantly do `(... messages)`, when we could do something like `(say! :copy)`, which would lead to less repetitive code, I think. But it's just a taste thing, I guess, feel free to ignore this thought and implement just your original idea instead if you don't agree with it 👌

**Comment by AbhinavOmprakash** [comment]
I agree, there are a lot of redundant prints, 
but there are some prints like this.

`(println (:change messages) name "...")`

which would mean you either have to modify `say!` to take variadic args or you'd have to do `(println (say :change) name "...")`

**Comment by askonomm** [comment]
What about:

```clojure
(defn- say!
  ([name]
    ...print-only)
  ([name & args)
    (println ...message (apply str args)))
```

Or something like this?

**Comment by AbhinavOmprakash** [comment]
i meant, create a new issue for `say!` and make that a good first issue 😅

**Comment by askonomm** [comment]
![](https://media.giphy.com/media/XeLcgh8gT8o0F5SQ8i/giphy.gif)
