### ISSUE TITLE
minor bug: `copy-password` will print "password copied" even if the password is not copied

### ISSUE THREAD

**Issue by AbhinavOmprakash** [askonomm/shh#5]
https://github.com/askonomm/shh/blob/f20977dc6c4124a72a10bcb7c5d3a1ae837a20fd/src/shh/core.clj#L47-L57

I discovered this while testing the function. I'm on windows, and the function doesn't support that, yet it says password copied successfully.

**Comment by askonomm** [comment]
I wouldn't say this is a bug per se since there isn't even a windows executable, only Linux and Mac OS (https://github.com/askonomm/shh/releases/tag/2021.10.13).
